name: "harmonization_clinicalcombat"
description: ComBAT harmonization of clinical MRI data. It's a ComBAT
  implementations for adapting sites to a reference site
  along with ready-to-run scripts to prepare datasets,
  fit a model, apply the harmonization and analyze the outputs.
  Two harmonization methods are available pairwise (linear) and clinic (non-linear).
keywords:
- Harmonization
- Pairwise
- Clinical
- ComBAT
tools:
- "clinical-ComBAT":
    description: ""
    homepage: "https://github.com/scil-vital/clinical-ComBAT"
    doi: "10.48550/arXiv.2511.04871"
    licence: "CC BY-NC-SA 4.0"
    identifier: ""
args:
  - method:
      type: string
      description: |
        Harmonization strategy to use: clinic (non-linear) or pairwise (linear)
      default: clinic
  - bundles:
      type: list
      description: |
        List of bundles subset used to plot. By default all bundles
        in the csv input file were used to compute model harmonization.
      default: all
  - limit_age_range:
      type: boolean
      description: Drop reference subjects outside the moving age range.
      default: disabled
  - ignore_sex:
      type: boolean
      description: |
        Remove sex variable when estimating the model.
        If all subjects have the same value, it will be automatically applied.
      default: disabled
  - ignore_handedness:
      type: boolean
      description: |
        Remove handedness variable when estimating the model.
        If all subjects have the same value, it will be automatically applied.
      default: disabled
  - no_empiral_bayes:
      type: boolean
      description: |
        Ignore the empirical Bayesian estimate
      default: disabled
  - regul_ref:
      type: integer
      description:  |
        Ridge penalty applied to reference regression.
        Parameter use for clinic method only.
      default: 0
  - regul_mov:
      type: string
      description: |
        Moving site penalty or auto-tuning.
        Parameter use for clinic method only.
      default: -1
  - degree:
      type: integer
      description: |
        Polynomial degree used for age.
        It depend on method used (1 for parwise, 2 for clinic)
      default: None
      choices: "1,2"
  - nu:
      type: integer
      description: |
        Variance hyperparameter for the moving site.
        Parameter use for clinic method only.
      default: 5
      choices: "tournier07, descoteaux07, descoteaux07_legacy, tournier07_legacy"
  - tau:
      type: integer
      description: |
        Covariate hyperparameter for the moving site.
        Parameter use for clinic method only.
      default: 2
  - degree_qc:
      type: integer
      description: QC model degree override (0 reuses the harmonization degree).
      default: 0
input:
    - ref_site:
        type: file
        description: |
          CSV for Reference site data for one metric, all bundles and subjects.
          Must include sid,site,bundle,metric,mean,age,sex,handedness,disease.
          The Disease column must include at least the label HC.
        pattern: "*.{csv,csv.gz}"
    - mov_site:
        type: file
        description: |
          CSV for moving site data for one metric, all bundles and subjects.
          Must include sid,site,bundle,metric,mean,age,sex,handedness,disease.
          If one of the expected covariates (sex, handedness) is missing,
          assign the same value to all subjects (1 or 0).
          The Disease column must include at least the label HC.
        pattern:  "*.{csv,csv.gz}"
output:
  model:
    - "*.model.csv":
        type: file
        description: Harmonization fitted model.
        pattern: "*.model.csv"
        ontologies:
          - edam: http://edamontology.org/format_3752
  harmonizedsite:
    - "*.csv.gz":
        type: file
        description: Moving site harmonized data.
        pattern: "*.csv.gz"
        ontologies:""
  bdqc:
    - "*.bhattacharrya.txt":
        type: file
        description: Bhattacharrya distance (QC) data before and after harmonization.
        pattern: "*.bhattacharrya.txt"
        ontologies:
          - edam: http://edamontology.org/format_2330
  figures:
    - "*png":
        type: file
        description: Figure plotting reference and moving site data before and after harmonization as well as the harmonization model.
        pattern: "*png"
        ontologies:
          - edam: http://edamontology.org/format_3603
  versions:
    - versions.yml:
      type: file
      description: File containing software versions
      pattern: versions.yml
      ontologies:
      - edam: http://edamontology.org/format_3750  # YAML
authors:
- "@manonedde"
maintainers:
- "@manonedde"
