# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: betcrop_dwi2mask
description: Obtain a brain mask from a diffusion weighted image using MRtrix3's dwi2mask
keywords:
  - nifti
  - betcrop
  - dwi2mask
tools:
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      doi: 10.1016/j.neuroimage.2019.116137
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
        mandatory: true
    - dwi:
        type: file
        description: Nifti dwi file to mask
        pattern: "*.{nii,nii.gz}"
        mandatory: true
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        mandatory: true
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        mandatory: true
        ontologies: []
output:
  mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_dwi_mask.nii.gz":
          type: file
          description: mask brain-extracted and cropped.
          pattern: "*_dwi_mask.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@AntoineTheb"
