# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "atlas_iit"
description: |
  This module downloads the IIT Human Brain Atlas depending on what is already available
  the user. If the user does not have anything available locally, the inputs should simply
  be channels of empty lists (e.g. ATLAS_IIT(Channel.of([]), Channel.of([]), Channel.of([]))).
  In that case, the module will download the FA, B0 maps and will download/compute the bundle masks
  from the IIT website. If the user has only some of these maps available, they can provide
  them as inputs and the module will only download what is missing.

  Even if the user has the entire IIT atlas available locally, they can still provide the
  paths to those files as inputs and the module will act as a single output from which you
  can get use those files.

  The Mean FA and Mean B0 maps as well as the bundle density maps used are in
  182x218x182 matrix size. The Atlas is in the MNI152NLin6Asym template space
  (1mm resolution).
keywords:
- atlas
- iit
- neuroimaging
- bundles
- template
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""

input:
  - iit_b0:
      type: file
      description: |
        Path to the Mean B0 map of the IIT Human Brain Atlas.
        If not provided, the module will download it.
      mandatory: false
      ontologies: []
  - iit_fa:
      type: file
      description: |
        Path to the Mean FA map of the IIT Human Brain Atlas.
        If not provided, the module will download it.
      mandatory: false
  - iit_bundles:
      type: file
      description: |
        Path to the folder containing the IIT bundle masks.
        If not provided, the module will download and create them
        from the recommended bundle density maps thresholds.
      mandatory: false
      ontologies: []
output:
  bundles:
    - "iit_bundles/*.nii.gz":
        type: file
        description: IIT binary bundle masks.
        pattern: "iit_bundles/*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
  b0:
    - "*_b0.nii.gz":
        type: file
        description: Mean B0 map of the IIT Human Brain Atlas.
        pattern: "*_b0.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
  fa:
    - "*_fa.nii.gz":
        type: file
        description: Mean FA map of the IIT Human Brain Atlas.
        pattern: "*_fa.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
- "@levje"
maintainers:
- "@levje"
