name: "harmonization_formatstats"
description: |
  The harmonization modules currently expect a CSV file with the following columns:
  "sid,site,bundle,metric,mean,age,sex,handedness,disease".
  And a separate CSV file PER metric.

  However, in other nf-neuro modules (e.g. stats/metricsinroi or bundle/stats), the
  output stats files are in TSV format with the following columns:
  "sid,roi,<covariates>,metric1,metric2,...".

  This module creates the bridge between these two formats, allowing to convert
  from one to the other. You then have two options:
  1) Format the TSV stats file (possibly coming from the stats/metricsinroi or bundle/stats
      modules) into the CSV format expected by the harmonization modules
      (set ext.inverse = false, the default value).
  2) Format the CSV stats files (possibly coming from the harmonization modules) into a TSV format
      that can be easily read by MultiQC or other downstream tools (set ext.inverse = true).
keywords:
  - harmonization
  - stats
  - format
  - tsv
  - csv
  - qc
tools:
  - pandas:
      description: "Python package used to manipulate the input and output tabular data for this module."
      homepage: https://pypi.org/project/pandas/
      identifier: ""

input:
  - tabular_files:
      type: file
      description: |
        Input tabular stats files to be reformatted for before or after harmonization.
        - To format to use in harmonization, provide one or more TSV files with columns
          "sid,roi,<covariates>,metric1,metric2,...".
        - To format after harmonization, provide one or more CSV files (one per metric)
          with columns: "sid,site,bundle,metric,mean,<covariates>".
      pattern: "*.{tsv,csv}"
      ontologies:
        - edam: http://edamontology.org/format_3464 # JSON format
args:
  covariates:
    type: file
    description: |
      List of columns that are not considered metrics in the input tabular files.
      These columns will be kept unchanged (except for renaming the columns) while
      the other columns (i.e. the metrics and their values) will be pivotted or
      unpivotted.
      Default: ["sample", "roi", "site", "age", "sex", "handedness", "disease"]
    pattern: "*.{nii,nii.gz}"
    ontologies:
      - edam: http://edamontology.org/format_4001 # NIFTI format
  inverse:
    type: boolean
    description: |
      If false (the default), format the input TSV files into the CSV format expected by the harmonization modules.
      If true, format the input CSV files (coming from harmonization) into a TSV format
      that can be easily read by MultiQC or other downstream tools.
    default: false
  value_col_name:
    type: string
    description: |
      Name of the column containing the metric values in the CSV files.
      Default: "mean"
    default: "mean"
  metric_col_name:
    type: string
    description: |
      Name of the column containing the metric names in the CSV files.
      Default: "metric"
    default: "metric"
  suffix:
    type: string
    description: |
      Suffix to use for the output files based on the operation performed.
      The output files will be named as "site.metric.<suffix>.csv" or "site.<suffix>.tsv" (inverse).
      Default: "raw" (inverse = false) or "harmonized" (inverse = true).
    default: "raw"
output:
  raw_files:
    - "*.csv":
        type: file
        description: |
          Raw stats files in CSV format (Harmonization ready). Output only
          if "ext.inverse = false" (the default).
        pattern: "*.raw.csv"
        ontologies:
          - edam: http://edamontology.org/format_3752 # CSV format
  harmonized_files:
    - "*.tsv":
        type: file
        description: |
          Harmonized stats files in TSV format (MultiQC ready format). Output only
          if "ext.inverse = false" (the default).
        pattern: "*.harmonized.tsv"
        ontologies:
          - edam: http://edamontology.org/format_3475 # TSV format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@levje"
maintainers:
  - "@levje"
