# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: connectivity_decompose
description: Divide a tractogram into its various connections using a brain parcellation(labels).
  The hdf5 output format allows to store other information required for connectivity,
  such as the associated labels.
keywords:
  - nifti
  - connectivity
  - decompose
  - scilpy
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - trk:
        type: file
        description: Tractogram to decompose.
        pattern: "*.{trk, tck, vtk, fib, dpy}"
        ontologies: []
    - labels:
        type: file
        description: brain parcellation. Labels must have 0 as background. Volumes must
          have isotropic voxels.
        pattern: "*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
args:
  - no_pruning:
      type: boolean
      description: If true, the command will not perform pruning of the connections. By default, the command will perform pruning to remove spurious connections.
      default: false
  - no_remove_loops:
      type: boolean
      description: If true, the command will not remove loops in the connections. By default, the command will remove loops to ensure that each connection is represented as a simple path between two regions.
      default: false
  - no_remove_outliers:
      type: boolean
      description: If true, the command will not remove outliers in the connections. By default, the command will remove outliers to improve the quality of the resulting connectivity matrix.
      default: false
  - no_remove_duplicates:
      type: boolean
      description: If true, the command will not remove duplicate streamlines in the connections. By  
        default, the command will remove duplicate streamlines to reduce redundancy in the resulting connectivity matrix.
      default: false
  - no_remove_curv:
      type: boolean
      description: If true, the command will not remove streamlines with high curvature in the connections. By default, the command will remove streamlines with high curvature to improve the quality of the resulting connectivity matrix.
      default: false
  - min_len:
      type: integer
      description: Minimum length of streamlines to keep in the connections. By default, streamlines shorter than 10 mm will be removed to improve the quality of the resulting connectivity matrix.
      default: 20.0
  - max_len:
      type: integer
      description: Maximum length of streamlines to keep in the connections. By default, streamlines longer than 250 mm will be removed to improve the quality of the resulting connectivity matrix.
      default: 200.0
  - outlier_threshold:
      type: number
      description: Threshold for outlier removal in the connections. By default, streamlines that are more than 3 standard deviations away from the mean will be considered outliers and removed to improve the quality of the resulting connectivity matrix.
      default: 0.6
  - max_angle:
      type: number
      description: Maximum angle between consecutive segments of a streamline to keep in the connections. By default, streamlines with angles greater than 45 degrees will be removed to improve the quality of the resulting connectivity matrix.
      default: 330
  - max_curv:
      type: number
      description: Maximum curvature of streamlines to keep in the connections. By default, streamlines with curvature greater than 1 mm^-1 will be removed to improve the quality of the resulting connectivity matrix.
      default: 10
  - single_thread:
      type: boolean
      description: If true, the command will be run in single-threaded mode. By default, the command will use multiple threads based on the number of CPUs allocated to the task.
      default: false
output:
  hdf5:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*__decomposed.h5":
          type: file
          description: |
            Output hdf5 file where each bundles is a group with key'LABEL1_LABEL2'.
            The array_sequence format cannot be stored directly in a hdf5, so each
            group is composed of 'data', 'offsets' and 'lengths' from the array
            sequence. The 'data' is stored in VOX/CORNER for simplicity and efficiency.
          pattern: "*__decomposed.h5"
          ontologies: []
  labels_list:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*__labels_list.txt":
          type: file
          description: Save the labels list as text file.
          pattern: "*__labels_list.txt"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@ThoumyreStanislas"
maintainers:
  - "@ThoumyreStanislas"
